import Head from 'next/head';
import styles from '../styles/Home.module.css';
import styled from 'styled-components';
import { Header } from '../components'

export default function Components() {
  return (
    <div className={styles.container}>
      <Head>
        <title>The E-commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        
        <h1>Components</h1>
        <p className={styles.p}>Mussum Ipsum, cacilds vidis litro abertis.<br />Si u mundo tá muito paradis?<br />Toma um mé que o mundo vai girarzis! <br />Praesent malesuada urna nisi, quis volutpat erat hendrerit non. <br />Nam vulputate dapibus.<br /> Todo mundo vê os porris que eu tomo, mas ninguém vê os tombis que eu levo! <br />Suco de cevadiss deixa as pessoas mais interessantis.</p>
      </main>

      <footer className={styles.footer}>
        Footer
      </footer>
    </div>
  )
}
